# Generated by Django 2.1.4 on 2018-12-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narudzbina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='narudzbina',
            name='braintree_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
