# Generated by Django 2.1.4 on 2018-12-18 18:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuponi', '0003_auto_20181218_1623'),
        ('narudzbina', '0002_narudzbina_braintree_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='narudzbina',
            name='kupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narudzbine', to='kuponi.Kupon'),
        ),
        migrations.AddField(
            model_name='narudzbina',
            name='popust',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
