# Generated by Django 2.1.3 on 2018-12-02 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(db_index=True, max_length=25)),
                ('slug', models.SlugField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'kategorija',
                'verbose_name_plural': 'kategorije',
                'ordering': ('ime',),
            },
        ),
        migrations.CreateModel(
            name='Proizvod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(db_index=True, max_length=200)),
                ('opis', models.TextField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('slika', models.ImageField(blank=True, default='proizvodi/no_image.png', upload_to='proizvodi/%Y/%m/%d')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kreirano', models.DateTimeField(auto_now_add=True)),
                ('azurirano', models.DateTimeField(auto_now=True)),
                ('dostupno', models.BooleanField(default=True)),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proizvodi', to='prodavnica.Kategorija')),
            ],
            options={
                'ordering': ('-kreirano',),
            },
        ),
        migrations.AlterIndexTogether(
            name='proizvod',
            index_together={('id', 'slug')},
        ),
    ]
