# Generated by Django 2.1.3 on 2018-12-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodavnica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proizvod',
            old_name='price',
            new_name='cena',
        ),
    ]
