# Generated by Django 2.1.4 on 2018-12-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodavnica', '0002_auto_20181202_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proizvod',
            options={'ordering': ('-kreirano',), 'verbose_name_plural': 'proizvodi'},
        ),
    ]
