# Generated by Django 2.1.4 on 2018-12-24 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodavnica', '0003_auto_20181206_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategorijaTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('ime', models.CharField(db_index=True, max_length=25)),
                ('slug', models.SlugField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'kategorija Translation',
                'db_table': 'prodavnica_kategorija_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProizvodTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('ime', models.CharField(db_index=True, max_length=200)),
                ('opis', models.TextField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'proizvod Translation',
                'db_table': 'prodavnica_proizvod_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='kategorija',
            options={'verbose_name': 'kategorija', 'verbose_name_plural': 'kategorije'},
        ),
        migrations.AlterModelOptions(
            name='proizvod',
            options={},
        ),
        migrations.RemoveField(
            model_name='kategorija',
            name='ime',
        ),
        migrations.RemoveField(
            model_name='kategorija',
            name='slug',
        ),
        migrations.AlterIndexTogether(
            name='proizvod',
            index_together=set(),
        ),
        migrations.AddField(
            model_name='proizvodtranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='prodavnica.Proizvod'),
        ),
        migrations.AddField(
            model_name='kategorijatranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='prodavnica.Kategorija'),
        ),
        migrations.RemoveField(
            model_name='proizvod',
            name='ime',
        ),
        migrations.RemoveField(
            model_name='proizvod',
            name='opis',
        ),
        migrations.RemoveField(
            model_name='proizvod',
            name='slug',
        ),
        migrations.AlterUniqueTogether(
            name='proizvodtranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='kategorijatranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
