# Generated by Django 2.1.4 on 2018-12-18 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=50, unique=True)),
                ('vazi_od', models.DateTimeField()),
                ('vazi_do', models.DateTimeField()),
                ('aktivno', models.BooleanField(default=True)),
                ('popust', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator('100'), django.core.validators.MinValueValidator('0')])),
            ],
        ),
    ]
