# Generated by Django 2.1.4 on 2018-12-18 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuponi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kupon',
            options={'verbose_name_plural': 'Kuponi'},
        ),
        migrations.AlterField(
            model_name='kupon',
            name='popust',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator('100'), django.core.validators.MinValueValidator('0')]),
        ),
    ]
