# Generated by Django 2.1.4 on 2018-12-18 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuponi', '0002_auto_20181218_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kupon',
            name='popust',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
